mappings:
  Testimonial: DFT\SilverStripe\Testimonials\Model\Testimonial
  TestimonialHolderPage: DFT\SilverStripe\Testimonials\Model\TestimonialHolderPage
  TestimonialWidget: DFT\SilverStripe\Testimonials\Model\TestimonialWidget
  MemberTestimonialExtension: DFT\SilverStripe\Testimonials\Extensions\MemberTestimonialExtension
  TestimonialsAdmin: DFT\SilverStripe\Testimonials\CMS\TestimonialsAdmin
